farmapp/models.py
"""

Project: farmdb

File Name: tables

Author: Zachary Romer, zach@scharp.org

Creation Date: 8/24/19

Version: 1.0

Purpose:

Special Notes:

"""
from datetime import datetime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.types import DateTime
from sqlalchemy.dialects.postgresql import JSONB
from marshmallow_sqlalchemy import ModelSchema
from flask_sqlalchemy import SQLAlchemy

from farmapp.setup_app import db

class PlantType(db.Model):

    __tablename__ = 'plant_types'

    id = db.Column(db.Integer, db.Sequence('plant_type_id_seq'), primary_key=True)
    name = db.Column(db.String, nullable=False)
    species = db.Column(db.String, nullable=False)
    subspecies = db.Column(db.String, nullable=True)
    suggested_sun_reqs = db.Column(db.String, nullable=True)
    suggested_harvest_reqs = db.Column(db.String, nullable=True)
    grown_before = db.Column(db.Boolean, nullable=True)
    native_to = db.Column(db.String, nullable=True)
    notes = db.Column(db.String, nullable=True)

    def __repr__(self):
        return f"<PlantType>(id='{self.name}', name='{self.species}'"

class PlantTypeSchema(ModelSchema):
    class Meta:
        model = PlantType

class Planted(db.Model):

    __tablename__ = 'planted'

    #TODO set date_planted to default time
    id = db.Column(db.Integer, db.Sequence('planted_id_seq'), primary_key=True)
    plant_type_id = db.Column(db.Integer, db.ForeignKey('plant_types.id'))
    date_planted = db.Column(db.DateTime, nullable=True)
    date_harvested = db.Column(db.DateTime, nullable=True)
    harvest_yield = db.Column(db.Integer, nullable=True)
    quality = db.Column(db.String, nullable=True)
    notes = db.Column(db.String, nullable=True)

farmapp/flaskfront/forms.py
from wtforms.validators import DataRequired, Length
from wtforms import Form, StringField, BooleanField, TextAreaField, SubmitField

standard_validators = [DataRequired(), Length(0, 255)]


class PlantTypeInputForm(Form):

    name = StringField('Name')
    species = StringField('Species')
    subscpecies = StringField('Subspecies', description='Any subspecies information to differentiate this plant from others of the same species')
    suggested_sun_reqs = TextAreaField('Suggested Sun Requirements')
    have_grown_before = BooleanField('Have you grown this before?')
    native_to = StringField('This plant is native to')
    notes = TextAreaField('Any other notes')
    submit = SubmitField('Submit', )

farmapp/__init__.py
"""

Project: farmdb

File Name: __init__.py

Author: Zachary Romer, zach@scharp.org

Creation Date: 8/24/19

Version: 1.0

Purpose:

Special Notes:

"""

farmapp/api/__init__.py
from .views import plants

farmapp/api/views.py
from flask import Blueprint, flash, render_template, current_app, request, jsonify
from flask_restplus import Api

from farmapp.flaskfront.forms import PlantTypeInputForm
from farmapp.models import PlantType, PlantTypeSchema
from farmapp.setup_app import get_db_session

plants = Blueprint('plant_types', __name__, url_prefix='/plant_types', template_folder='templates')
api = Api(plants)

@plants.route('/species/add', methods=['GET', 'POST'])
def add_plant_type():
    db = get_db_session()
    form = PlantTypeInputForm(request.form)


    if request.method == 'POST':
        if form.validate():
            plant_type = PlantType(
                name=form.name.data,
                species=form.species.data,
            )
            db.session.add(plant_type)
            db.session.commit()
            flash('Created new plant type')
        else:
            flash('you dun fucked up')


    return render_template('addplant.html', form=form)


@plants.route('/view', methods=['GET'])
def get_plant_types():
    db = get_db_session()
    plants = db.session.query(PlantType).all()
    data = PlantTypeSchema().dump(plants)

    return jsonify(data), 201

farmapp/app.py
"""

Project: farmdb

File Name: farmapp.py

Author: Zachary Romer, zach@scharp.org

Creation Date: 8/24/19

Version: 1.0

Purpose:

Special Notes:

"""
import os
from typing import List


from flask import Flask, Blueprint

from farmapp.api import views as api_views
from farmapp.flaskfront import views as front_views

from farmapp.setup_app import api, app, db

blueprints = [front_views.frontend, api_views.plants]


def blueprints_fabric(app: Flask, blueprint: List[Blueprint]):
    for b in blueprint:

        app.register_blueprint(b)

def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    import logging

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    # info_log = os.path.join(app.config["LOG_FOLDER"], "info.log")
    # info_file_handler = logging.l.RotatingFileHandler(
    #     info_log, maxBytes=100000, backupCount=10
    # )
    # info_file_handler.setLevel(logging.INFO)
    # info_file_handler.setFormatter(
    #     logging.Formatter(
    #         "%(asctime)s %(levelname)s: %(message)s " "[in %(pathname)s:%(lineno)d]"
    #     )
    # )
    # app.logger.addHandler(info_file_handler)
    #
    # # Testing
    # # farmapp.logger.info("testing info.")
    # # farmapp.logger.warn("testing warn.")
    # # farmapp.logger.error("testing error.")
    #
    # mail_handler = logging.handlers.SMTPHandler(
    #     app.config["MAIL_SERVER"],
    #     app.config["MAIL_USERNAME"],
    #     app.config["ADMINS"],
    #     "O_ops... %s failed!" % app.config["PROJECT"],
    #     (app.config["MAIL_USERNAME"], app.config["MAIL_PASSWORD"]),
    # )
    # mail_handler.setLevel(logging.ERROR)
    # mail_handler.setFormatter(
    #     logging.Formatter(
    #         "%(asctime)s %(levelname)s: %(message)s " "[in %(pathname)s:%(lineno)d]"
    #     )
    # )
    # app.logger.addHandler(mail_handler)

#app, api = create_app()


if __name__ == '__main__':

    blueprints_fabric(app, blueprints)

    configure_logging(app)
    db.create_all()

    api.app.run(debug=True)

farmapp/flaskfront/__init__.py
from .views import frontend, frontend_api

farmapp/flaskfront/views.py
from flask import Blueprint, render_template
from flask_restplus import Api

frontend = Blueprint('flaskfront', __name__, template_folder='templates')
frontend_api = Api(frontend)


@frontend.route('/')
def index():
    return render_template('index.html')


@frontend.route('/docs/', defaults={'path': 'index'})
@frontend.route('/docs/<path:path>/', endpoint='page')
def page(path):
    # Documentation views
    return render_template('index.html')

farmapp/frontend/views.py
from flask import Blueprint, render_template
from flask_restplus import Api

frontend = Blueprint('frontend', __name__, template_folder='templates')
frontend_api = Api(frontend)


@frontend.route('/')
def index():
    return render_template('index.html')


@frontend.route('/docs/', defaults={'path': 'index'})
@frontend.route('/docs/<path:path>/', endpoint='page')
def page(path):
    # Documentation views
    return render_template('index.html')

farmapp/templates/base.html
<!DOCTYPE html>
<html lang="{{ lang|default("en") }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="/static/favicon.png">

  <title>{% block title %}{{ page_title|default(('New site')) }}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/bootstrap/dist/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome/css/font-awesome.min.css') }}">
  {% block include_css %}
  {% endblock %}
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <script src="{{ url_for('static', filename='libs/jquery/dist/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='libs/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='code.js') }}"></script>
  {% block include_js %}
  {% endblock %}

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
{% block extramedia %}{% endblock %}
{% include "counter.html" %}

</head>
<body {% block body_id %}{% endblock %}>
<div id="wrap">

  {% include "nav.html" %}

  {% block fullcontent %}

  <div class="container">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {# Body #}
    {% block content %}{% endblock %}
  </div>
  {% endblock %}

</div> <!-- /wrap -->

<div id="footer">
  <div class="container">
    <p>&copy; 2014 <a href="{{ url_for('frontend.index', _external=True) }}">{{("New site")}}</a></p>
  </div>
</div>

</body>
</html>

farmapp/templates/counter.html
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXX']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

farmapp/templates/nav.html
<div class="navbar navbar-default" role="navigation">
  <div class="navbar-header">

    <a class="navbar-brand {% if url_for('frontend.index') == request.path %}active{% endif %}" href="{{ url_for('frontend.index') }}">{{ ("Site") }}</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li {% if url_for('frontend.index') == request.path %}class="active"{% endif %}><a href="{{ url_for('frontend.index') }}">{{ ("Splash page") }}</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li {% if url_for('frontend.page') == request.path %}class="active"{% endif %}><a href="{{ url_for('frontend.page') }}"><i class="fa fa-book"></i> {{ ("About site ") }}</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li {% if url_for('plants.add_plant_type') == request.path %}class="active"{% endif %}><a href="{{ url_for('plants.add_plant_type') }}"><i class="fa fa-book"></i> {{ ("Add plant ") }}</a></li>
    </ul>
  </div><!--/.nav-collapse -->
</div>